use std::{fs, process::Command};

fn main() {
    // Copy overlay.dll to bin folder for bundling
    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    let target_dir = std::env::current_dir()
        .unwrap()
        .join("target")
        .join(&profile);
    
    let overlay_dll = target_dir.join("overlay.dll");
    let dest_dir = std::env::current_dir().unwrap().join("bin");
    let dest_path = dest_dir.join("overlay.dll");

    let renderer_executable = target_dir.join("overlay_renderer.exe");
    let renderer_dest_path = dest_dir.join("overlay_renderer.exe");

    // Only copy if it exists (it might not be built yet during initial check)
    if overlay_dll.exists() {
        let _ = std::fs::create_dir_all(&dest_dir);
        let _ = std::fs::copy(overlay_dll, dest_path);
    }

    if renderer_executable.exists() {
        let _ = std::fs::create_dir_all(&dest_dir);
        let _ = std::fs::copy(renderer_executable, renderer_dest_path);
    }

    git_metadata_build();

    tauri_build::build()
}

fn git_metadata_build() {
    let hash = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .unwrap_or_else(|| "unknown".to_string());

    let count = Command::new("git")
        .args(["rev-list", "--count", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .unwrap_or_else(|| "0".to_string());

    let timestamp = chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string();

    let version = fs::read_to_string("../version.txt").unwrap_or_else(|_| "0.0.0".to_string());
    let mut build_type = std::env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    if build_type != "debug" {
        // read version.txt generated by version.cjs to determine if this is a stable or pre-release build
        if version.contains("-") {
            build_type = "pre-release".to_string();
        } else {
            build_type = "stable".to_string();
        }
    }

    println!("cargo:rustc-env=GIT_HASH={}", hash.trim());
    println!("cargo:rustc-env=BUILD_NUMBER={}", count.trim());
    println!("cargo:rustc-env=BUILD_VERSION={}", version.trim());
    println!("cargo:rustc-env=BUILD_TYPE={}", build_type);
    println!("cargo:rustc-env=BUILD_TIME={}", timestamp);
}
